
# trying out using YAML as config file
# YAML supports commenting unlike JSON
# it is more user-friendly for documentation purposes
# other than this, yamlFile and JSON can both be read as
# a dictionary format, thus little changes are needed 
# to be made to the actual code

dataSource    : ../data/

output:
  location    : ../data/intermediate/ensemble_features
  posfix      : '' # give a tag to this run, appended to runID, default to empty
    